development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: CNCManagerD
  pool: 5
  username: root
  password: izklop669
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: CNCManagerT
  pool: 5
  username: root
  password: izklop669
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: CNCManager
  pool: 5
  username: root
  password: izklop669